# Generated by Django 4.1.3 on 2022-12-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_chatmessage_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='timestamp',
        ),
    ]
